### ISSUE TITLE
Array Index of Bound Exception when trying to remove selected position

### ISSUE THREAD

**Issue by rajajawahar** [sephiroth74/HorizontalVariableListView#115]
java.lang.IndexOutOfBoundsException: Invalid index 59, size is 55
                                                                                                              at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                                              at java.util.ArrayList.get(ArrayList.java:308)
                                                                                                              at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
                                                                                                              at it.sephiroth.android.sample.horizontalvariablelistviewdemo.SimpleHListActivity$TestAdapter.getItemId(SimpleHListActivity.java:202)
                                                                                                              at it.sephiroth.android.library.widget.AbsHListView.confirmCheckedPositionsById(AbsHListView.java:4958)
                                                                                                              at it.sephiroth.android.library.widget.AbsHListView.handleDataChanged(AbsHListView.java:5006)
                                                                                                              at it.sephiroth.android.library.widget.HListView.layoutChildren(HListView.java:1601)
                                                                                                              at it.sephiroth.android.library.widget.AbsHListView.onLayout(AbsHListView.java:1792)
                                                                                                              at android.view.View.layout(View.java:14834)
                                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                                              at android.view.View.layout(View.java:14834)
                                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                                              at android.view.View.layout(View.java:14834)
                                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                                              at android.view.View.layout(View.java:14834)
                                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                                              at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
                                                                                                              at android.view.View.layout(View.java:14834)
                                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                                              at android.view.View.layout(View.java:14834)
                                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
                                                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                                              at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by sephiroth74** [comment]
Sorry but this repo isn't mantained anymore. You should switch to RecyclerView

**Comment by rajajawahar** [comment]
Do you singleChoice recyclerview sample code??
