### ISSUE TITLE
Long press on items is throwing NullPointerExceptions

### ISSUE THREAD

**Issue by saket** [sephiroth74/HorizontalVariableListView#71]
First of all, thank you so much for this fantastic custom ListView. 

Everything is working perfectly, except for one thing. Long-pressing on a child is throwing NullPointerExceptions. Here's the stack-trace:

``` java
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ActionMode$Callback.onCreateActionMode(android.view.ActionMode, android.view.Menu)' on a null object reference
            at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2678)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2620)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:665)
            at android.view.View.startActionMode(View.java:4536)
            at it.sephiroth.android.library.widget.AbsHListView.performLongPress(AbsHListView.java:2572)
            at it.sephiroth.android.library.widget.AbsHListView$CheckForLongPress.run(AbsHListView.java:2529)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
```

The issue is happening at line #2572 of AbsHListView.java. 

**Current workaround**: By setting the choice mode of HListView to anything other than `ListView.CHOICE_MODE_MULTIPLE_MODAL` so that the line where the NPE is being thrown is never reached.

**Comment by cyberrob** [comment]
you could just set the HListView `ListView.CHOICE_MODE_SINGLE`  to skip the exception.
