### ISSUE TITLE
NPE crashed

### ISSUE THREAD

**Issue by afeilulu** [sephiroth74/HorizontalVariableListView#72]
after scrolling list item,refilling list, crash happened sometime.Anyone know about this ? killing my brain for two days, please help.
java.lang.NullPointerException
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2495)
            at it.sephiroth.android.library.widget.AbsHListView.dispatchDraw(AbsHListView.java:1806)
            at it.sephiroth.android.library.widget.HListView.dispatchDraw(HListView.java:3548)
            at android.view.View.draw(View.java:10986)
            at it.sephiroth.android.library.widget.AbsHListView.draw(AbsHListView.java:2956)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.getDisplayList(View.java:10420)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.getDisplayList(View.java:10420)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.getDisplayList(View.java:10420)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10986)
            at android.widget.FrameLayout.draw(FrameLayout.java:450)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2127)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:842)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2046)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1770)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2587)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by DevCCC** [comment]
I also got the same issue
